# GitHub Secret Scanning Configuration
# This file configures which paths are excluded from GitHub's secret scanning

paths-ignore:
  # Environment file templates - contain placeholder examples only
  - '.env.example'
  - '.env.template'
  - '.env.*.example'

  # Documentation - may reference API key formats for educational purposes
  - 'docs/**'
  - 'README.md'

  # Examples and templates
  - 'examples/**'
  - 'templates/**'

# Note: These exclusions prevent alerts for false positives
# Actual secrets should NEVER be committed to any branch
# All real credentials must be in .env.local (which is in .gitignore)
